/*Exercise 2.1 - We have a lot of students in this course! Let’s
create a for loop to create a student tracking system so we know
How many students we have. In your js file, create a list variable
called students. Fill it with the names “Sofia", "Elizabeth", "Sasha",
"Samantha", "Abigail", "Lorena", "Ayesha", "Adeyo", "Emil"*/
var student = ["Sofia","Elizabeth", "Sasha","Samantha", "Abigail", "Lorena", "Ayesha", "Adeyo", "Emil"];

/*Exercise 2.2 - Create a for loop to count through the number of
students within the students array. Hint: Use the .length method
instead of counting the number of students manually!*/
for(i = 0; i<student.length;i++){
    console.log(student[i]);
}
/*Exercise 2.3 - Let’s say we can only run a small class. Create
variables for class size (0), maxClassSize (7) and an empty
classList. Use a while loop to add random students to the
classList so long as the number of students in the new class is
less than the maximum size.*/
classSize = 0
maxClassSize = 7
classList = []
while(classSize < maxClassSize){
    // generate random student name using a randomly generated index which we get by multyplying Math.random 
    // and the length of the array so we never go out of that bound.
    // then we then round down to a whole number 
    const randomStudent = student[Math.floor(Math.random() * student.length)];
    // add students to class list with push method
    classList.push(randomStudent)
    // do an increment
    classSize++

}
console.log(classList)

/*Math.random() is a JavaScript function that returns a random floating-point number between 0 (inclusive) and 1 (exclusive). 
  In other words, it returns a number that is greater than or equal to 0 and less than 1.

Math.floor() is a JavaScript function that rounds a number down to the nearest integer. For example, Math.floor(3.9) returns 3.

Math.random() * studentArray.length generates a random floating-point number between 0 and the length of the studentArray. 
For example, if the length of studentArray is 8, Math.random() * studentArray.length could return any number between 0 and 7.999999.

Math.floor(Math.random() * student.length) takes the random number generated by Math.random() * student.length
and rounds it down to the nearest integer. This ensures that the result is an integer between 0 and the
 length of student array- 1 (inclusive), which can be used as an index to select a random element from the array.

In the context of the exercise, this expression is used to randomly select an element from the studentArray. 
The selected element is then added to the classList using the push() method.*/